[project]
name = "transpressor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "einops>=0.8.2",
    "evotorch>=0.6.1",
    "gym-pusht>=0.1.6",
    "h5py>=3.16.0",
    "hdf5plugin>=7.0.0",
    "imageio>=2.37.4",
    "imageio-ffmpeg>=0.6.0",
    "omegaconf>=2.3.1",
    "pillow>=12.3.0",
    "pymunk<7",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
    "transformers>=5.16.1",
    "wandb>=0.28.2",
]

[project.scripts]
transpressor = "transpressor:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
