n_epochs: 100
lr: 1e-5
min_lr: 1e-6
warmup_steps: 1000
batch_size: 128
num_frames: 4
max_hop_length: 1
frameskip: 5
num_workers: 4
log_to_wandb: False 

loss_weights:
  prediction_weight: 1.0
  prediction_sigreg_weight: 0.1

transpressor:
  input_dim: 2
  hidden_dim: 64
  condition_dim: 16
  depth: 6
  heads: 8
  dim_head: 64
  mlp_dim: 2048
  dropout: 0.1
  output_proj: True

ar_predictor:
  input_dim: 192
  hidden_dim: 192
  condition_dim: 192
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0

naive_action_embedder:
  embed_dim: 192

pixel_preprocessor:
  model_name: "facebook/deit-tiny-patch16-224"

pixel_encoder:
  model_name: "facebook/deit-tiny-patch16-224"

datapath: "data/pusht_expert_train.h5"

device: "mps"

world_size: 1

push_to_hub: True
hf_repo_id: "kompallia/lewm_checkpoints"
